name: matchpoint
channels:
- conda-forge
dependencies:
- python=3.14
- numpy=2.3
- matplotlib-base=3.10
- pathlib2=2.3
- pyyaml=6.0
- scikit-image=0.26
- scipy=1.17
- tqdm=4.67
- scikit-learn=1.8
- shapely=2.1
- xarray=2026.2
- sphinx=5.3
- sphinx-book-theme=1.1
- pytest
- pytest-datadir
- twine
- setuptools_scm>=8.1
- pip:
  - build
